#!/usr/bin/env python3
"""Run dependency-free repository and skill release checks."""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CALVER = re.compile(r"^v\d{4}\.\d{1,2}\.\d{1,2}(?:\.\d+)?$")
REQUIRED_FILES = (
    "SKILL.md",
    "agents/openai.yaml",
    "references/01-orientation/utility-contract.md",
    "references/01-orientation/official-source-policy.md",
    "references/02-execution/implementation-workflow.md",
    "references/02-execution/analytics-tags.md",
    "references/02-execution/media-tags.md",
    "references/02-execution/cmp-consent.md",
    "references/02-execution/naming-and-reuse.md",
    "references/03-judgement/acceptance-and-handoff.md",
    "README.md",
    "CHANGELOG.md",
    "LICENSE",
    "CONTRIBUTING.md",
    "SECURITY.md",
    "pyproject.toml",
    ".github/workflows/ci.yml",
    "scripts/build_skill_package.py",
)
STALE_FILES = (
    "references/execution-contract.md",
    "references/official-source-policy.md",
    "references/analytics-tags.md",
    "references/media-tags.md",
    "references/cmp-consent.md",
    "references/naming-and-reuse.md",
    "references/validation-scenarios.md",
)
FORBIDDEN_ARTIFACT_NAMES = {
    ".coverage",
    ".pytest_cache",
    ".ruff_cache",
    "__pycache__",
    "release",
}


def read(relative: str) -> str:
    return (ROOT / relative).read_text(encoding="utf-8")


def parse_frontmatter() -> tuple[str, str]:
    text = read("SKILL.md")
    if not text.startswith("---\n"):
        raise ValueError("SKILL.md frontmatter is missing")
    _, raw, _ = text.split("---", 2)
    values: dict[str, str] = {}
    for line in raw.splitlines():
        if not line.strip():
            continue
        key, separator, value = line.partition(":")
        if not separator:
            raise ValueError(f"invalid frontmatter line: {line}")
        values[key.strip()] = value.strip().strip('"')
    if list(values) != ["name", "description"]:
        raise ValueError("frontmatter must contain only name and description")
    if values.get("name") != "configure-gtm":
        raise ValueError("frontmatter name must be configure-gtm")
    if not values.get("description"):
        raise ValueError("frontmatter description is empty")
    return values["name"], values["description"]


def check_links() -> list[str]:
    errors: list[str] = []
    skill = read("SKILL.md")
    links = re.findall(r"\]\(([^)]+)\)", skill)
    for link in links:
        if link.startswith(("http://", "https://")):
            continue
        if not (ROOT / link).exists():
            errors.append(f"SKILL.md references missing resource: {link}")

    reference_files = {
        path.relative_to(ROOT).as_posix()
        for path in (ROOT / "references").rglob("*")
        if path.is_file()
    }
    linked_references = {link for link in links if link.startswith("references/")}
    for reference in sorted(reference_files - linked_references):
        errors.append(f"reference is not directly routed from SKILL.md: {reference}")
    return errors


def check_required_files() -> list[str]:
    errors = [f"missing required file: {path}" for path in REQUIRED_FILES if not (ROOT / path).exists()]
    errors.extend(f"stale file remains: {path}" for path in STALE_FILES if (ROOT / path).exists())
    for path in ROOT.rglob("*"):
        if path.name in FORBIDDEN_ARTIFACT_NAMES:
            errors.append(f"generated artifact must be removed: {path.relative_to(ROOT)}")
        if path.suffix in {".pyc", ".pyo"}:
            errors.append(f"generated bytecode must be removed: {path.relative_to(ROOT)}")
    return errors


def check_content() -> list[str]:
    errors: list[str] = []
    skill = read("SKILL.md")
    utility = read("references/01-orientation/utility-contract.md")
    judgement = read("references/03-judgement/acceptance-and-handoff.md")
    readme = read("README.md")
    changelog = read("CHANGELOG.md")
    required_terms = (
        "01 - Orientation",
        "02 - Execution",
        "03 - Judgement",
        "dedicated GTM workspace",
        "Server-side GTM",
        "browser/server deduplication",
    )
    errors.extend(f"SKILL.md missing required term: {term}" for term in required_terms if term not in skill)
    utility_terms = ("## Audience", "## Objective", "## Current use cases", "## Inputs", "## Outputs", "## Boundaries")
    errors.extend(f"utility contract missing section: {term}" for term in utility_terms if term not in utility)
    judgement_terms = ("## Completion definition", "## Judgement statuses", "## Static validation matrix", "## Consent proof", "## Handoff output")
    errors.extend(f"judgement reference missing section: {term}" for term in judgement_terms if term not in judgement)
    readme_terms = ("## Who It Serves", "## Utility Objective", "## Inputs", "## Outputs", "## Workflow Architecture", "## Boundaries", "## Related Skills", "## Release Checks")
    errors.extend(f"README missing section: {term}" for term in readme_terms if term not in readme)
    if "## 2026.7.13" not in changelog:
        errors.append("CHANGELOG is missing the current release section")
    if re.search(r"Scope excludes[^.]*\b(server-side|deduplication)\b", skill, re.I):
        errors.append("server-side/deduplication appears in the permanent exclusion sentence")
    if "future extensions of this skill" not in skill.lower():
        errors.append("future capability boundary is not explicit")
    if len(skill.splitlines()) >= 500:
        errors.append("SKILL.md exceeds the 500-line guidance limit")
    release_text = "\n".join(read(path) for path in ("SKILL.md", "README.md", "CHANGELOG.md"))
    if re.search(r"TODO|\[TODO\]", release_text, re.I):
        errors.append("release-facing files contain placeholders")
    return errors


def check_release_notes(path: Path) -> list[str]:
    if not path.exists():
        return [f"release notes file does not exist: {path}"]
    text = path.read_text(encoding="utf-8")
    headings = ("Why This Release Matters", "What Changed", "What Users Should Do", "Validation", "Known Limits")
    return [f"release notes missing heading: {heading}" for heading in headings if f"### {heading}" not in text]


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--tag")
    parser.add_argument("--release-notes", type=Path)
    args = parser.parse_args()
    errors: list[str] = []
    try:
        _, description = parse_frontmatter()
        if "expert web analyst" not in description.lower():
            errors.append("frontmatter does not identify the expert web analyst audience")
    except ValueError as exc:
        errors.append(str(exc))
    errors.extend(check_required_files())
    errors.extend(check_links())
    errors.extend(check_content())
    if args.tag and not CALVER.fullmatch(args.tag):
        errors.append(f"invalid CalVer release tag: {args.tag}")
    if args.release_notes:
        errors.extend(check_release_notes(args.release_notes))
    if errors:
        for error in errors:
            print(f"ERROR: {error}", file=sys.stderr)
        print(f"Release check: FAIL ({len(errors)} error(s))")
        return 1
    print(f"Release check: PASS ({len(REQUIRED_FILES)} required files, {len(read('SKILL.md').splitlines())} SKILL.md lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
